name: HTML Check

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Required will all actions
    - name: Checks Valid HTML5
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: tests/valid/

    - name: Testing Options
      id: valid
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: tests/valid/
        format: json
        log_level: INFO
        extra: -lll
        css: true

    - name: Check Blacklist
      id: blacklist
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: tests/
        blacklist: invalid

    - name: Check Failure
      id: invalid
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: tests/invalid/
        log_level: INFO
        css: true
      continue-on-error: true